services:
  hmi:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    restart: unless-stopped

  bridge:
    build: ./bridge
    ports:
      - "8081:8081"
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - "c 188:* rmw"   # ajusta este número al que viste arriba
      - "c 166:* rmw"
    restart: unless-stopped

  simulator:
    build: ./simulator
    ports:
      - "8082:5000"
    restart: unless-stopped